name: Auto-Merge Codex PRs

on:
  pull_request:
    types:
      - labeled
      - opened
      - synchronize

permissions:
  pull-requests: write
  contents: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'codex')
    steps:
      - name: Enable GitHub Auto-Merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
