name: Auto Label Codex PRs

on:
  pull_request:
    types: [opened]

jobs:
  label-codex:
    runs-on: ubuntu-latest
    steps:
    - name: Auto-label PRs from codex branches
      if: startsWith(github.head_ref, 'codex/')
      uses: actions-ecosystem/action-add-labels@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        labels: codex
