name: Auto-Merge Codex PRs

on:
  pull_request:
    types:
      - labeled

jobs:
  automerge:
    if: github.event.label.name == 'codex'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Auto-merge Codex PRs
        uses: "peter-evans/enable-pull-request-automerge@v3"
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
