name: AI Profit Suite - Full Auto Ops

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  daily-summary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install requirements
        run: |
          pip install -r requirements.txt || true
          pip install fpdf openai pandas || true

      - name: Debug - List Files
        run: ls -R

      - name: Generate and save summary
        run: |
          mkdir -p output
          set -x
          python scripts/generate_summary.py || echo "Script failed"

      - name: Upload summary artifact
        - uses: actions/upload-artifact@v4
        with:
          name: Daily Summary
          path: output/daily_summary.pdf
