name: AI Summary Generator - Every 30 Min

on:
  schedule:
    - cron: '*/30 * * * *'  # Every 30 minutes
  workflow_dispatch:

jobs:
  generate-summary:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install openai pandas fpdf || true

      - name: Debug - List Files
        run: ls -R

      - name: Generate and save summary
        run: |
          mkdir -p output
          set -x
          python scripts/generate_summary.py || echo "⚠️ Script failed but continuing"

      - name: Upload summary artifact
        uses: actions/upload-artifact@v4
        with:
          name: Daily Summary
          path: output/daily_summary.pdf
