name: Generate Daily Learning Prompt

on:
  schedule:
    - cron: "0 2 * * *"  # Every day at 2:00 AM UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install openai

      - name: Run Python script
        run: python daily_learning_prompt.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Upload output
        uses: actions/upload-artifact@v4
        with:
          name: daily-learning
          path: output/daily_learning.txt
