# daily_learning_prompt.py

import os
import openai
from datetime import datetime

openai.api_key = os.getenv("OPENAI_API_KEY")

prompt = f"Generate a daily learning idea for {datetime.now().strftime('%B %d, %Y')} that teaches something useful about AI, coding, or productivity."

response = openai.Completion.create(
    model="text-davinci-003",
    prompt=prompt,
    temperature=0.7,
    max_tokens=200
)

result = response.choices[0].text.strip()

# Save output
os.makedirs("output", exist_ok=True)
with open("output/daily_learning.txt", "w") as f:
    f.write(result)

print("✅ Daily prompt generated successfully.")
