name: AI Learning Prompt - Every 30 Min

on:
  schedule:
    - cron: '*/30 * * * *'  # Every 30 minutes
  workflow_dispatch:

jobs:
  generate-learning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install openai fpdf pandas

      - name: Run learning prompt generator
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python scripts/daily_learning_prompt.py

      - name: Upload learning PDF
        uses: actions/upload-artifact@v3
        with:
          name: LearningPrompt
          path: output/daily_prompt.pdf
